---
output: pdf_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)

library(icon)

```

# texblocks

Building blocks for TeX tables

## Idea

Assemble LaTeX tabular environments using simple operations.

This would enable us to create any table layout with a consistent user API.

Defining a new class of R element `tabular` that is the basic structure of the language.

## Proposed Syntax

Defining a new class of R element `tabular` that is the basic structure of the language.

### Joining elements

Let `t1` and `t2` be two objects of class tabular.

|  |   |
|:--:|:--:|
| `t1 + t2`  |`r icon::fa("square")` `r icon::fa("square")`|


|  |   |
|:--:|:--:|
| `t1 | t2` |`r icon::fa('square')` `|` `r icon::fa('square')`|


|  |   |
|:--:|:--:|
| `t1 || t2` |`r icon::fa('square')` `||` `r icon::fa('square')`|


|  |   |
|:--:|:--:|
||`r icon::fa('square')`|
|`t1 / t2`||
||`r icon::fa('square')`|


|  |   |
|:--:|:--:|
| |`r icon::fa('square')`|
|`t1 - t2`| - |
||`r icon::fa('square')`|


Using this language creating a table can be broken down to cell level

`t1 =(``r icon::fa('square')`` + ``r icon::fa('square')`` + ``r icon::fa('square')``) / (``r icon::fa('square')`` + ``r icon::fa('square')`` + ``r icon::fa('square')``)`

would be translated to 

```
1 & 2 & 3 \\
4 & 5 & 6
```

`t2 = (``r icon::fa('square')`` + ``r icon::fa('square')`` + ``r icon::fa('square')``)` `-` `(``r icon::fa('square')`` + ``r icon::fa('square')`` + ``r icon::fa('square')``)`

would be translated to 

```
7 & 8 & 9 \\ \hline
10 & 11 & 12
```

making their combination a natural extension

`t1 + t2`

would translate to 

```
1 & 2 & 3 & 7 & 8 & 9 \\ cline{4-6}
4 & 5 & 6 & 10 & 11 & 12
```

### Mutations

A set of mutation verbs can be defined to mainpulate within table actions, eg

  - multirow
  - multicolumn
  
### Aesthetics

A set of aesthetic elements can be defined to control the table and cell level attributes, eg

  - font: colour, size, face
  - background colour
