---
title: "Building Blocks"
author: "Jonathan Sidi"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(texblocks)
library(texPreview)

```
 
```{r,include=FALSE}
tex_opts$set(returnType = 'html')
tex_opts$append(list(cleanup='tex'))
```

## Single blocks

```{r}
as.tb('$\\alpha$')
as.tb('aaa')
```

## Replicate

```{r}
rep(as.tb('$\\alpha$'),3)

```
 
## List 
 
```{r}
lapply(1:3,as.tb)

```

## Converting from different classes

### data.frame
```{r}
iris%>%
  head(5)%>%
  as.tb()

```

```{r dataframe,echo=FALSE}
iris%>%
  head(5)%>%
  as.tb()%>%
  tabular()%>%
  texPreview::tex_preview()
```
 
### matrix 

```{r}
matrix(0,3,3)%>%
  as.tb()

```

```{r matrix, echo=FALSE}
matrix(0,3,3)%>%
  as.tb()%>%
  tabular()%>%
  texPreview::tex_preview()

```

### sparse matrix
 
```{r}
Matrix::bdiag(Matrix::Diagonal(2), matrix(1:3, 3,4), diag(3:2))%>%
  as.tb()

```

```{r smatrix, echo=FALSE}
Matrix::bdiag(Matrix::Diagonal(2), matrix(1:3, 3,4), diag(3:2))%>%
  as.tb()%>%
  tabular()%>%
  texPreview::tex_preview()

```


## Converting to different classes

### as.data.frame

```{r}
matrix(1:9,3,3)%>%
  as.tb()%>%
  as.data.frame()
```

## Combining blocks

### Horizontal

```{r}
x <- as.tb('$\\alpha$')
y <- as.tb('aaa')
z <- as.tb('$\\beta$')

x1 <- x+y+z
```

```{r horizontal, echo=FALSE}
x1%>%
  tabular()%>%
  texPreview::tex_preview()
```

### Vertical

```{r}
x/y/z
```

```{r vertical, echo=FALSE}
(x/y/z)%>%
  tabular()%>%
  texPreview::tex_preview()
```

Combined texblocks are texblocks themselves, thus can be further combined.

```{r}
x2 <- x1 / x1 # 2x3 object
x2 + x2
```

```{r vertical2, echo=FALSE}
(x2 + x2)%>%
  tabular()%>%
  texPreview::tex_preview()
```

### Unequal blocks
 
```{r}
x3 <- x2/x2 # 4x3 object

# 4x6 object with empty block in the lower right hand side of the table
x2 + x3
```

```{r unequal, echo=FALSE}
(x2 + x3)%>%
  tabular()%>%
  texPreview::tex_preview()
```

## Creating a tabular object

```{r tabular}
# default alignment
x1%>%
  texblocks::tabular()%>%
  texPreview::tex_preview()

```
 
```{r unequaltabular}
# manual alignment
x1%>%
  texblocks::tabular(align = '|cc|c')%>%
  texPreview::tex_preview()
```