---
title: "Using texblocks"
author: "Jonathan Sidi"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette: 
    keep_md: true
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  fig.path = "figures"
)
```

```{r}
library(texblocks)
library(texPreview)

```
 
```{r,include=FALSE}

if(!dir.exists('figures'))
  dir.create('figures')

tex_opts$set(returnType= 'html',
             resizebox = FALSE,
             fileDir = 'figures',
             opts.html = list(width='50%',height='50%'))

tex_opts$append(list(cleanup='tex'))
```

```{r}
x <- '$\\alpha$'
y <- 'cindy'
class(x) <- 'tb'
class(y) <- 'tb'
```
 
```{r}
x1 <- x+y+x
x1
```
 
```{r}
x1 + x1
x1 / x1
x1 - x1
```
 
```{r}
x2 <- x1 / x1
x2 + x2
```
 
```{r}
x3 <- x2/x2
x2 + x3
```

```{r}
as.data.frame( x2 + x3 )
```

```{r}
texblocks::tabular( x2 + x3,align = 'c|c|c|c|c|c')
```

# Compiled

```{r, echo=TRUE,results='asis'}
texPreview::texPreview(tabular(x1 ,'c|c|c'),stem = "tb1")

```
 
```{r, echo=TRUE,results='asis'}
texPreview::texPreview(tabular(x2 ,'c|c|c'),stem = "tb2")

```
 
```{r, echo=TRUE,results='asis'}
texPreview::texPreview(tabular(x3 ,'c|c|c'),stem = "tb3")

```
 
```{r, echo=TRUE,results='asis'}
texPreview::texPreview(tabular(x2-x2 ,'c|c|c'),stem = "tb4")

```
 
```{r, echo=TRUE,results='asis'}
texPreview::texPreview(tabular(x2 + x3 ,'c|c|c|c|c|c'),stem = "tb5")

```
 
```{r, echo=TRUE,results='asis'}
texPreview::texPreview(tabular(x3 + x3,'c|c|c|c|c|c'),stem = "tb6")

```
 
```{r, echo=TRUE,results='asis'}
texPreview::texPreview(tabular((x1+x1)-(x3 + x3)/(x3 + x3) ,'|c|ccccc'),stem = "tb7")

```